baseURL = "https://chemie-lernen.org/"
languageCode = "de-de"
title = "Chemie Lernen - 📖 Offene, 🖱️ Interaktive und 🥽 Immersive Lerninhalte"
theme = "hugo-cards"

# Disable LiveReload in production
disableLiveReload = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  github = "tobias-weiss-ai-xr"
  custom_css = ["css/custom.css", "css/dark-mode.css"]
  custom_js = ["js/dark-mode.js"]
  defaultImage = "recent-article_001.jpg"
  footer_description = "Chemie Lernen - Ihre Plattform für innovative Chemie-Lernräume in Virtual Reality. Machen Sie komplexe chemische Konzepte greifbar und erlebbar."

[params.meta]
  keywords = "Chemie Lernen, VR Chemieunterricht, Virtual Reality Bildung, Chemie lernen online, interaktiver Chemieunterricht, digitale Bildung, VR Lernräume, Chemie studieren, innovative Chemie, immersive Bildung"

author = "Chemie Lernen Team"

[[menu.main]]
    name = "Periodensystem"
    url = "/perioden-system-der-elemente/"
    weight = 10
[[menu.main]]
    name = "Molekülstudio"
    url = "/molekuel-studio/"
    weight = 30
[[menu.main]]
    name = "Roadmap"
    url = "/pages/roadmap/"
    weight = 40
[[menu.main]]
    name = "Über uns"
    url = "/pages/about/"
    weight = 50
[[menu.main]]
    name = "Kontakt"
    url = "/pages/contact/"
    weight = 60

